modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/nanonestor/melter-block/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
credits="Code inspirtation from the amazing Create mod"
mod_authors="${mod_authors}"
description='''
A fork of the original Melter mod by Oierbravo

A simple melter block that turn blocks into liquid.
Intended for modpacks. Use as you see fit.
Recipes easily added via datapack or KubeJS - See project Curseforge website or Github for details.

https://www.curseforge.com/minecraft/mc-mods/melter-block
https://github.com/nanonestor/melter-block

'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.melter]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.melter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.melter]]
    modId="create"
    mandatory=false
    versionRange="[0.5.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.melter]]
    modId="jei"
    mandatory=false
    versionRange="[11.2.0.254,)"
    ordering="NONE"
    side="BOTH"